/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai3;


import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author nguye
 */
public class jlistbai3 extends javax.swing.JFrame {

    /**
     * Creates new form jlistbai3
     */
    public jlistbai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlisttrai = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistphai = new javax.swing.JList<>();
        righttt = new javax.swing.JButton();
        allright = new javax.swing.JButton();
        lefttt = new javax.swing.JButton();
        allleft = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btthem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DS");

        jScrollPane1.setViewportView(jlisttrai);

        jScrollPane2.setViewportView(jlistphai);

        righttt.setText(">");
        righttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightttActionPerformed(evt);
            }
        });

        allright.setText(">>");
        allright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allrightActionPerformed(evt);
            }
        });

        lefttt.setText("<");
        lefttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftttActionPerformed(evt);
            }
        });

        allleft.setText("<<");
        allleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allleftActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Danh sách môn thể thao");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Danh sách môn yêu thích");

        btthem.setText("+");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btthem)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(righttt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allright, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(lefttt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allleft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(righttt)
                        .addGap(18, 18, 18)
                        .addComponent(allright)
                        .addGap(18, 18, 18)
                        .addComponent(lefttt)
                        .addGap(18, 18, 18)
                        .addComponent(allleft)))
                .addGap(18, 18, 18)
                .addComponent(btthem)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rightttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightttActionPerformed
        // TODO add your handling code here:
        int y = jlisttrai.getSelectedIndex();
        ListModel mTrai = jlisttrai.getModel();
        ListModel mPhai = jlistphai.getModel();
        
        List <String> listTrai = new ArrayList<>();
        List <String> listPhai = new ArrayList<>();
        
        for( int i = 0 ; i < mTrai.getSize();i++ )
            listTrai.add((String) mTrai.getElementAt(i));
        
        for( int i = 0 ; i < mPhai.getSize();i++ )
            listPhai.add((String) mPhai.getElementAt(i));
        
        listPhai.add((String) mTrai.getElementAt(y));
        String remove;
        remove = listTrai.remove(y);
        
        String[] ardata = listTrai.toArray(new String[0]);
        String[] arData = listPhai.toArray(new String[0]);
        jlistphai.setListData(arData);
        jlisttrai.setListData(ardata);
        
    }//GEN-LAST:event_rightttActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        
        // TODO add your handling code here:
        String thethao = JOptionPane.showInputDialog(this,"nhap mon the thao : ");
        ListModel mTrai = jlisttrai.getModel();
        List <String> listTrai = new ArrayList<>();
        for( int i = 0 ; i < mTrai.getSize();i++ )
            listTrai.add((String) mTrai.getElementAt(i));
        listTrai.add(thethao);
        String[] ardata = listTrai.toArray(new String[0]);
        jlisttrai.setListData(ardata);
    }//GEN-LAST:event_btthemActionPerformed

    private void allrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allrightActionPerformed
        // TODO add your handling code here:

        ListModel mTrai = jlisttrai.getModel();
        ListModel mPhai = jlistphai.getModel();
        
        List <String> listTrai = new ArrayList<>();
        List <String> listPhai = new ArrayList<>();
        
        for( int i = 0 ; i < mTrai.getSize();i++ )
            listTrai.add((String) mTrai.getElementAt(i));
        
        for( int i = 0 ; i < mPhai.getSize();i++ )
            listPhai.add((String) mPhai.getElementAt(i));
        
        listPhai.addAll(listTrai);
        listTrai.removeAll(listTrai);
        
        
        String[] ardata = listTrai.toArray(new String[0]);
        String[] arData = listPhai.toArray(new String[0]);
        jlistphai.setListData(arData);
        jlisttrai.setListData(ardata);
    }//GEN-LAST:event_allrightActionPerformed

    private void allleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allleftActionPerformed
        // TODO add your handling code here:
        ListModel mTrai = jlisttrai.getModel();
        ListModel mPhai = jlistphai.getModel();
        
        List <String> listTrai = new ArrayList<>();
        List <String> listPhai = new ArrayList<>();
        
        for( int i = 0 ; i < mTrai.getSize();i++ )
            listTrai.add((String) mTrai.getElementAt(i));
        
        for( int i = 0 ; i < mPhai.getSize();i++ )
            listPhai.add((String) mPhai.getElementAt(i));
        
        listTrai.addAll(listPhai);
        listPhai.removeAll(listPhai);
        
        
        String[] ardata = listTrai.toArray(new String[0]);
        String[] arData = listPhai.toArray(new String[0]);
        jlistphai.setListData(arData);
        jlisttrai.setListData(ardata);
    }//GEN-LAST:event_allleftActionPerformed

    private void leftttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftttActionPerformed
        // TODO add your handling code here:
        int y = jlistphai.getSelectedIndex();
        ListModel mTrai = jlisttrai.getModel();
        ListModel mPhai = jlistphai.getModel();
        
        List <String> listTrai = new ArrayList<>();
        List <String> listPhai = new ArrayList<>();
        
        for( int i = 0 ; i < mTrai.getSize();i++ )
            listTrai.add((String) mTrai.getElementAt(i));
        
        for( int i = 0 ; i < mPhai.getSize();i++ )
            listPhai.add((String) mPhai.getElementAt(i));
        
        listTrai.add((String) mPhai.getElementAt(y));
        String remove;
        remove = listPhai.remove(y);
        
        String[] ardata = listTrai.toArray(new String[0]);
        String[] arData = listPhai.toArray(new String[0]);
        jlistphai.setListData(arData);
        jlisttrai.setListData(ardata);
    }//GEN-LAST:event_leftttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jlistbai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jlistbai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jlistbai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jlistbai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jlistbai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allleft;
    private javax.swing.JButton allright;
    private javax.swing.JButton btthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlistphai;
    private javax.swing.JList<String> jlisttrai;
    private javax.swing.JButton lefttt;
    private javax.swing.JButton righttt;
    // End of variables declaration//GEN-END:variables
}
